// src/components/blob/blob.tsx
import {svgPath} from 'utils/blobs';
import {generateRandomColor} from 'utils/color';
import {randBetween} from 'utils/random';

import styles from './blob.scss';

const offsets = [0, 20, 70, 100],
    generateGradient = () => {
        const stops: { offset: number; color: string }[] = [];

        for (let i = 0; i < 4; i++) {
            stops.push({
                offset: offsets[i]!,
                color: generateRandomColor(),
            });
        }

        return {
            id: Math.random().toString(),
            rotate: randBetween(0, 180),
            stops,
        };
    },
    generateSize = () => randBetween(200, 250),
    generatePath = (size: number, fillId: string, shadowId?: string) => ({
        d: svgPath({
            seed: Math.random(),
            extraPoints: randBetween(3, 8),
            randomness: randBetween(2, 5),
            size,
        }),
        fillId,
        shadowId,
    }),
    generateTransform = (size: number, i: number) =>
        ({'transform': `translate(${i == 1 ? size / 2 : 0}px, ${i == 2 ? size / 2 : 0}px)`});

export default function Blob(props: object): JSX.Element {
    const gradients = [generateGradient(), generateGradient(), generateGradient()],
        size = generateSize(),
        paths = [
            generatePath(size, gradients[0]!.id!),
            generatePath(randBetween(size / 2, size / 1.1), gradients[1]!.id!),
            generatePath(randBetween(size / 2, size / 1.1), gradients[2]!.id!),
        ];

    return (
        <svg xmlns="http://www.w3.org/2000/svg" className={styles.svg} width={size} height={size}>
            <defs>
                {gradients.map(({id, stops, rotate}) =>
                    <linearGradient key={id} id={id} gradientTransform={`rotate(${rotate})`}>
                        {stops.map(({offset, color}, index) =>
                            <stop key={index} offset={`${offset}%`} stopColor={color}/>
                        )}
                    </linearGradient>
                )}
            </defs>
            {paths.map(({d, fillId, shadowId}, i) =>
                <path
                    key={i}
                    className={i > 0 ? styles['not-first'] : ''}
                    d={d}
                    fill={`url(#${fillId})`}
                    style={generateTransform(size / 3, i)}/>
            )}
        </svg>
    );
}

// src/components/Blob.svelte
<script context="module">
  import blob from 'blobs/v2/index.js';

  import { generateRandomColor } from '$utils/color';
  import { randBetween } from '$utils/random';

  const offsets = [0, 20, 70, 100],
    generateGradient = () => {
      const stops: { offset: number; color: string; stopOpacity: number }[] = [];

      for (let i = 0; i < 4; i++) {
        stops.push({
          offset: offsets[i]!,
          color: generateRandomColor(),
          stopOpacity: randBetween(0.2, 1),
        });
      }

      return {
        id: Math.random().toString(),
        stops,
      };
    },
    generateSize = () => randBetween(300, 450),
    generatePath = (maxSize: number, fillId: string) => ({
      d: blob.svgPath({
        seed: Math.random(),
        extraPoints: randBetween(3, 8),
        randomness: randBetween(2, 5),
        size: randBetween(maxSize / 3, maxSize / 1.5),
      }),
      fillId,
    }),
    generateTransform = (size: number, i: number) => {
      switch (i) {
        case 1:
          return `transform: translate(${size / 2}px, 0)`;

        case 2:
          return `transform: translate(0, ${size / 2}px)`;
      }
    };
</script>

<script>
  const gradients = [generateGradient(), generateGradient(), generateGradient()],
    size = generateSize(),
    paths = Array(3)
      .fill(null)
      .map((_, i) => generatePath(size, gradients[i]?.id!));
</script>

<svg xmlns="http://www.w3.org/2000/svg" width={size} height={size}>
  <defs>
    {#each gradients as { id, stops } (id)}
      <linearGradient {id}>
        {#each stops as { offset, color, stopOpacity }}
          <stop offset="{offset}%" stop-color={color} stop-opacity={stopOpacity} />
        {/each}
      </linearGradient>
    {/each}
  </defs>

  {#each paths as { d, fillId }, i}
    <path {d} fill="url(#{fillId})" style={generateTransform(size / 3, i)} />
  {/each}
</svg>
